/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaccount;

import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Rum
 */
public class BankGUI extends javax.swing.JFrame {

    private Bank bank;
    final Font font = new Font("Verdana", Font.PLAIN, 25);

    /**
     * Creates new form BankGUI
     */
    public BankGUI(Bank bank) {
        this.bank = bank;

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        UIManager.put(
                "FileChooser.saveButtonText", "Сохранить");
        UIManager.put(
                "FileChooser.cancelButtonText", "Отмена");
        UIManager.put(
                "FileChooser.fileNameLabelText", "Наименование файла");
        UIManager.put(
                "FileChooser.filesOfTypeLabelText", "Типы файлов");
        UIManager.put(
                "FileChooser.lookInLabelText", "Директория");
        UIManager.put(
                "FileChooser.saveInLabelText", "Сохранить в директории");
        UIManager.put(
                "FileChooser.folderNameLabelText", "Путь директории");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDollar = new javax.swing.JLabel();
        jLabelEuro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jButtonPutMoney = new javax.swing.JButton();
        jButtonWithDrawMoney = new javax.swing.JButton();
        jButtonCalcPercent = new javax.swing.JButton();
        jButtonTransferInToDollars = new javax.swing.JButton();
        jButtonTransfersInToEuro = new javax.swing.JButton();
        jPanelSum = new javax.swing.JPanel();
        jLabelSum = new javax.swing.JLabel();
        jPanelPercent = new javax.swing.JPanel();
        jLabelPercent = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemOpenNewAccount = new javax.swing.JMenuItem();
        jMenuItemChangeAccount = new javax.swing.JMenuItem();
        jMenuItemSetDollar = new javax.swing.JMenuItem();
        jMenuItemSetEuro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Программа: Счет в банке");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDollar.setText("Курс доллара : " + String.format("%.2f",bank.getDollarRate()));

        jLabelEuro.setText("Курс евро : " + String.format("%.2f",bank.getEuroRate()));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(295, 257));

        jLabelWelcome.setText("<html>Для продолжения <br> откройте новый счет</html>");
        jLabelWelcome.setToolTipText("");
        jLabelWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonPutMoney.setText("Положить деньги");
        jButtonPutMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPutMoneyActionPerformed(evt);
            }
        });

        jButtonWithDrawMoney.setText("Снять деньги ");
        jButtonWithDrawMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWithDrawMoneyActionPerformed(evt);
            }
        });

        jButtonCalcPercent.setText("Вычислить проценты");
        jButtonCalcPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcPercentActionPerformed(evt);
            }
        });

        jButtonTransferInToDollars.setText("Перевести в доллары");
        jButtonTransferInToDollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferInToDollarsActionPerformed(evt);
            }
        });

        jButtonTransfersInToEuro.setText("Перевести в евро");
        jButtonTransfersInToEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransfersInToEuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPutMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonWithDrawMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCalcPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTransferInToDollars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTransfersInToEuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPutMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonWithDrawMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCalcPercent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransferInToDollars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransfersInToEuro)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        jButtonPutMoney.setVisible(false);
        jButtonWithDrawMoney.setVisible(false);
        jButtonCalcPercent.setVisible(false);
        jButtonTransferInToDollars.setVisible(false);
        jButtonTransfersInToEuro.setVisible(false);

        jPanelSum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Остаток", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelSum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelSum.setText("jLabel2");

        javax.swing.GroupLayout jPanelSumLayout = new javax.swing.GroupLayout(jPanelSum);
        jPanelSum.setLayout(jPanelSumLayout);
        jPanelSumLayout.setHorizontalGroup(
            jPanelSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSumLayout.setVerticalGroup(
            jPanelSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSum)
        );

        jPanelPercent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Процент", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelPercent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelPercent.setText("jLabel2");

        javax.swing.GroupLayout jPanelPercentLayout = new javax.swing.GroupLayout(jPanelPercent);
        jPanelPercent.setLayout(jPanelPercentLayout);
        jPanelPercentLayout.setHorizontalGroup(
            jPanelPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPercentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPercent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPercentLayout.setVerticalGroup(
            jPanelPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPercent)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDollar)
                            .addComponent(jLabelEuro))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jPanelSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDollar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEuro)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelSum.setVisible(false);
        jPanelPercent.setVisible(false);

        jMenu.setText("Меню");

        jMenuItemOpen.setText("Открыть");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemOpen);

        jMenuItemSave.setText("Сохранить");
        jMenuItemSave.setEnabled(false);
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSave);

        jMenuItemOpenNewAccount.setText("Открыть новый счет");
        jMenuItemOpenNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenNewAccountActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemOpenNewAccount);

        jMenuItemChangeAccount.setText("Сменить владельца");
        jMenuItemChangeAccount.setEnabled(false);
        jMenuItemChangeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangeAccountActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemChangeAccount);

        jMenuItemSetDollar.setText("Курс доллара...");
        jMenuItemSetDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetDollarActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSetDollar);

        jMenuItemSetEuro.setText("Курс евро...");
        jMenuItemSetEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetEuroActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSetEuro);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenNewAccountActionPerformed
        InitializeAccountDialog initAccountDialog = new InitializeAccountDialog(bank, this);
        initAccountDialog.setVisible(true);
        initAccountDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemOpenNewAccountActionPerformed

    private void jButtonWithDrawMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWithDrawMoneyActionPerformed
        OperationWithdrawMoneyDialog withdrawMoneyDialog = new OperationWithdrawMoneyDialog(bank, this);
        withdrawMoneyDialog.setVisible(true);
        withdrawMoneyDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonWithDrawMoneyActionPerformed

    private void jButtonPutMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPutMoneyActionPerformed
        OperationPutMoneyDialog putMoneyDialog = new OperationPutMoneyDialog(bank, this);
        putMoneyDialog.setVisible(true);
        putMoneyDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonPutMoneyActionPerformed

    private void jButtonCalcPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcPercentActionPerformed
        bank.calculatePercent();
        updateLabelSum();
    }//GEN-LAST:event_jButtonCalcPercentActionPerformed

    private void jButtonTransferInToDollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferInToDollarsActionPerformed
        JOptionPane.showMessageDialog(this, "Сумма в долларах :" + bank.transferSumIntoDollars());

    }//GEN-LAST:event_jButtonTransferInToDollarsActionPerformed

    private void jButtonTransfersInToEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransfersInToEuroActionPerformed
        JOptionPane.showMessageDialog(this, "Сумма в евро :" + bank.transferSumIntoEuro());
    }//GEN-LAST:event_jButtonTransfersInToEuroActionPerformed

    private void jMenuItemSetDollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetDollarActionPerformed
        SetDollarDialog setDollarDialog = new SetDollarDialog(bank, this);
        setDollarDialog.setVisible(true);
        setDollarDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemSetDollarActionPerformed

    private void jMenuItemSetEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetEuroActionPerformed
        SetEuroDialog setEuroDialog = new SetEuroDialog(bank, this);
        setEuroDialog.setVisible(true);
        setEuroDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemSetEuroActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        JFileChooser fileopen = new JFileChooser();
        int ret = fileopen.showDialog(null, "Открыть файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            String stateOpen = bank.openFileTxt(file);
            initComponent();
            JOptionPane.showMessageDialog(this, stateOpen);
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed

        JFileChooser fileSave = new JFileChooser();
        String nameFile;
        fileSave.setFileSelectionMode(DIRECTORIES_ONLY);
        int ret = fileSave.showDialog(null, "Сохранить файлы");
        if (ret == JFileChooser.APPROVE_OPTION) {
            bank.saveInFileTxt(fileSave.getSelectedFile());
            JOptionPane.showMessageDialog(this, "Успешное сохранение в директорию "
                    + fileSave.getSelectedFile());

        }

    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemChangeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangeAccountActionPerformed
        ChangeAccountDialog changeAccountDialog = new ChangeAccountDialog(bank,this);
        changeAccountDialog.setVisible(true);
        changeAccountDialog.setLocationRelativeTo(null);        
    }//GEN-LAST:event_jMenuItemChangeAccountActionPerformed

    public void initComponent() {
        jButtonCalcPercent.setVisible(true);
        jButtonPutMoney.setVisible(true);
        jButtonTransferInToDollars.setVisible(true);
        jButtonTransfersInToEuro.setVisible(true);
        jButtonWithDrawMoney.setVisible(true);
        updateLabelWelcome();
        updateLabelSum();
        updateLabelPercent();
        jPanelSum.setVisible(true);
        jPanelPercent.setVisible(true);
        jMenuItemChangeAccount.setEnabled(true);
        jMenuItemSave.setEnabled(true);
    }

    public void setLabelSum(String sum) {
        jLabelSum.setText("<html><center>" + sum + " р.</center></html>");
    }    

    public void updateLabelPercent(){
        jLabelPercent.setText(bank.getPercent() + " %");
    }
    
    public void updateLabelWelcome(){
        jLabelWelcome.setText("<html><center> Добро пожаловать <br>" + bank.getOwnerName() + "</center></html>");
    }

    public void updateLabelSum() {
        jLabelSum.setText(String.format("%.2f", bank.getSum()));
    }

    public void updateLabelDollar() {
        jLabelDollar.setText("Курс доллара : " + String.format("%.2f", bank.getDollarRate()));
    }

    public void updateLabelEuro() {
        jLabelEuro.setText("Курс евро : " + String.format("%.2f", bank.getEuroRate()));
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcPercent;
    private javax.swing.JButton jButtonPutMoney;
    private javax.swing.JButton jButtonTransferInToDollars;
    private javax.swing.JButton jButtonTransfersInToEuro;
    private javax.swing.JButton jButtonWithDrawMoney;
    private javax.swing.JLabel jLabelDollar;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelPercent;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemChangeAccount;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemOpenNewAccount;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSetDollar;
    private javax.swing.JMenuItem jMenuItemSetEuro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPercent;
    private javax.swing.JPanel jPanelSum;
    // End of variables declaration//GEN-END:variables
}
