/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaccount;

import javax.swing.JOptionPane;

/**
 *
 * @author Rum
 */
public class OperationWithdrawMoneyDialog extends javax.swing.JDialog {
    
    private Bank bank;
    private BankGUI bankGUI;
    

    /**
     * Creates new form PutMoneyDialog
     */
    public OperationWithdrawMoneyDialog(Bank bank,BankGUI bankGUI) {
        this.bankGUI = bankGUI;
        this.bank = bank;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOkWithdrawMoney = new javax.swing.JButton();
        jLabelWithdrawtMoneyError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldWithdrawMoney = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Положить деньги");

        jButtonOkWithdrawMoney.setText("Ok");
        jButtonOkWithdrawMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkWithdrawMoneyActionPerformed(evt);
            }
        });

        jLabelWithdrawtMoneyError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelWithdrawtMoneyError.setText("Неккоректно");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Сумма", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldWithdrawMoney)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldWithdrawMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jLabelWithdrawtMoneyError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOkWithdrawMoney))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWithdrawtMoneyError)
                    .addComponent(jButtonOkWithdrawMoney))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelWithdrawtMoneyError.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkWithdrawMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkWithdrawMoneyActionPerformed

        String sumWithdrawMoney = jTextFieldWithdrawMoney.getText();
        if(Bank.isNumeric(sumWithdrawMoney) && Double.parseDouble(sumWithdrawMoney) > 0){
            if(bank.withdrawMoney(Double.parseDouble(sumWithdrawMoney))){                
                bankGUI.updateLabelSum();
                jLabelWithdrawtMoneyError.setVisible(false);                
            }else{
                JOptionPane.showMessageDialog(this, "Недостаточно средств");
            }
            dispose();
        }else
            jLabelWithdrawtMoneyError.setVisible(true);
    }//GEN-LAST:event_jButtonOkWithdrawMoneyActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOkWithdrawMoney;
    private javax.swing.JLabel jLabelWithdrawtMoneyError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldWithdrawMoney;
    // End of variables declaration//GEN-END:variables
}
