/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaccount;

import javax.swing.JOptionPane;

/**
 *
 * @author Rum
 */
public class SetEuroDialog extends javax.swing.JDialog {
    
    private Bank bank;
    private BankGUI bankGUI;
    

    /**
     * Creates new form PutMoneyDialog
     * @param bank
     * @param bankGUI
     */
    public SetEuroDialog(Bank bank,BankGUI bankGUI) {
        this.bankGUI = bankGUI;
        this.bank = bank;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSetEuroOk = new javax.swing.JButton();
        jLabeSetEuroError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSetEuro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Задать курс доллара");

        jButtonSetEuroOk.setText("Ok");
        jButtonSetEuroOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetEuroOkActionPerformed(evt);
            }
        });

        jLabeSetEuroError.setForeground(new java.awt.Color(255, 0, 0));
        jLabeSetEuroError.setText("Неккоректно");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Курс евро к рублю", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSetEuro, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSetEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeSetEuroError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSetEuroOk)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeSetEuroError)
                    .addComponent(jButtonSetEuroOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabeSetEuroError.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSetEuroOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetEuroOkActionPerformed

        String value = jTextFieldSetEuro.getText();
        if(Bank.isNumeric(value) && Double.parseDouble(value) > 0){
            bank.setEuroRate(Double.parseDouble(value));
            bankGUI.updateLabelEuro();
            jLabeSetEuroError.setVisible(false);            
            dispose();
        }else
            jLabeSetEuroError.setVisible(true);
    }//GEN-LAST:event_jButtonSetEuroOkActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSetEuroOk;
    private javax.swing.JLabel jLabeSetEuroError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldSetEuro;
    // End of variables declaration//GEN-END:variables
}
